# Agent Investment Platform - LLM Configuration
# This file configures available Large Language Models and their usage

# Default LLM Configuration
default:
  provider: "huggingface"  # Options: huggingface, ollama, openai, anthropic
  model: "microsoft/Phi-3-mini-4k-instruct"
  max_tokens: 4096
  temperature: 0.1
  timeout: 120

# Provider-specific configurations
providers:
  # Hugging Face Models (Free, automatically updated)
  huggingface:
    cache_dir: "${HF_HOME:-models/.huggingface_cache}"
    models_dir: "models"
    models:
      - name: "microsoft/Phi-3-mini-4k-instruct"
        description: "Phi-3 Mini - Small, efficient model for general financial analysis"
        context_length: 4096
        size_gb: 2.4
        use_cases: ["general", "classification", "summarization"]
        model_type: "text-generation"
        repo_id: "microsoft/Phi-3-mini-4k-instruct"
      - name: "ProsusAI/finbert"
        description: "FinBERT - BERT model fine-tuned for financial sentiment analysis"
        context_length: 512
        size_gb: 0.4
        use_cases: ["sentiment", "classification", "news_analysis"]
        model_type: "text-classification"
        repo_id: "ProsusAI/finbert"
      - name: "sentence-transformers/all-MiniLM-L6-v2"
        description: "All-MiniLM-L6-v2 - Sentence embeddings for semantic similarity"
        context_length: 256
        size_gb: 0.1
        use_cases: ["embeddings", "similarity", "clustering"]
        model_type: "sentence-transformers"
        repo_id: "sentence-transformers/all-MiniLM-L6-v2"
      - name: "microsoft/codebert-base"
        description: "CodeBERT - Code understanding for trading strategy analysis"
        context_length: 512
        size_gb: 0.5
        use_cases: ["code_analysis", "strategy_validation"]
        model_type: "text-generation"
        repo_id: "microsoft/codebert-base"
    auto_update: true
    free_download: true
    timeout: 120

  # Local LLM via Ollama (Optional)
  ollama:
    host: "${OLLAMA_HOST:-http://localhost:11434}"
    models:
      - name: "llama3.1:8b"
        description: "Llama 3.1 8B - Fast and efficient for general analysis"
        context_length: 128000
        use_cases: ["general", "analysis", "summarization"]
      - name: "llama3.1:70b"
        description: "Llama 3.1 70B - High quality for complex reasoning"
        context_length: 128000
        use_cases: ["complex_analysis", "strategy", "research"]
      - name: "mistral:7b"
        description: "Mistral 7B - Alternative fast model"
        context_length: 32000
        use_cases: ["general", "classification"]
    timeout: "${OLLAMA_TIMEOUT:-300}"

  # OpenAI GPT Models
  openai:
    api_key: "${OPENAI_API_KEY}"
    models:
      - name: "gpt-4-turbo-preview"
        description: "GPT-4 Turbo - Latest and most capable model"
        context_length: 128000
        max_tokens: 4096
        use_cases: ["complex_analysis", "strategy", "research", "reports"]
      - name: "gpt-4"
        description: "GPT-4 - Reliable and capable for most tasks"
        context_length: 8192
        max_tokens: 4096
        use_cases: ["analysis", "strategy", "reports"]
      - name: "gpt-3.5-turbo"
        description: "GPT-3.5 Turbo - Fast and cost-effective"
        context_length: 16384
        max_tokens: 4096
        use_cases: ["general", "summarization", "classification"]
    timeout: 60

  # Anthropic Claude Models
  anthropic:
    api_key: "${ANTHROPIC_API_KEY}"
    models:
      - name: "claude-3-sonnet-20240229"
        description: "Claude 3 Sonnet - Balanced performance and capability"
        context_length: 200000
        max_tokens: 4096
        use_cases: ["analysis", "research", "reports"]
      - name: "claude-3-haiku-20240307"
        description: "Claude 3 Haiku - Fast and efficient"
        context_length: 200000
        max_tokens: 4096
        use_cases: ["general", "summarization", "classification"]
    timeout: 60

# Task-specific model assignments
task_assignments:
  # Financial analysis tasks
  stock_analysis:
    primary: "microsoft/Phi-3-mini-4k-instruct"
    fallback: "gpt-4-turbo-preview"
    temperature: 0.1

  market_sentiment:
    primary: "ProsusAI/finbert"
    fallback: "claude-3-sonnet-20240229"
    temperature: 0.2

  technical_analysis:
    primary: "microsoft/Phi-3-mini-4k-instruct"
    fallback: "gpt-4"
    temperature: 0.1

  # Research and strategy tasks
  investment_strategy:
    primary: "microsoft/Phi-3-mini-4k-instruct"
    fallback: "gpt-4-turbo-preview"
    temperature: 0.3

  risk_assessment:
    primary: "microsoft/Phi-3-mini-4k-instruct"
    fallback: "claude-3-sonnet-20240229"
    temperature: 0.1

  # Content generation tasks
  report_generation:
    primary: "microsoft/Phi-3-mini-4k-instruct"
    fallback: "gpt-4-turbo-preview"
    temperature: 0.2

  news_summarization:
    primary: "microsoft/Phi-3-mini-4k-instruct"
    fallback: "gpt-3.5-turbo"
    temperature: 0.1

  # Data processing tasks
  data_extraction:
    primary: "microsoft/Phi-3-mini-4k-instruct"
    fallback: "claude-3-haiku-20240307"
    temperature: 0.0

  classification:
    primary: "ProsusAI/finbert"
    fallback: "gpt-3.5-turbo"
    temperature: 0.0

  # Embedding and similarity tasks
  document_embeddings:
    primary: "sentence-transformers/all-MiniLM-L6-v2"
    fallback: "microsoft/Phi-3-mini-4k-instruct"
    temperature: 0.0

  semantic_search:
    primary: "sentence-transformers/all-MiniLM-L6-v2"
    fallback: "microsoft/Phi-3-mini-4k-instruct"
    temperature: 0.0# Model health monitoring
health_check:
  enabled: true
  interval_seconds: 300
  timeout_seconds: 30
  fallback_enabled: true

# Performance optimization
optimization:
  # Connection pooling
  max_connections: 10
  connection_timeout: 30

  # Caching
  cache_enabled: true
  cache_ttl_seconds: 3600

  # Rate limiting
  requests_per_minute: 60
  burst_limit: 10

# Logging and monitoring
logging:
  log_requests: true
  log_responses: false  # May contain sensitive data
  log_performance: true
  metrics_enabled: true

# Cost management (for paid APIs)
cost_management:
  daily_limit_usd: 50.0
  monthly_limit_usd: 1000.0
  alert_threshold: 0.8

# Security settings
security:
  api_key_rotation_days: 90
  request_encryption: true
  audit_log_enabled: true
